apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.namePrefix }}-env-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tridentprotect.labels" . | nindent 4 }}
data:
  TRIDENT_PROTECT_REGISTRY: "{{- if and (hasKey .Values.controller.image "registry") (not (eq .Values.controller.image.registry nil)) }}{{ .Values.controller.image.registry }}{{- else }}{{ .Values.imageRegistry }}{{- end }}"
  TRIDENT_PROTECT_TAG: "{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
  TRIDENT_PROTECT_SECRET: "{{- if .Values.imagePullSecrets }}{{ (index .Values.imagePullSecrets 0).name }}{{- else }}{{- end }}"
  TRIDENT_PROTECT_AUTOSUPPORT_ENABLED: "{{ .Values.autoSupport.enabled }}"
  TRIDENT_PROTECT_AUTOSUPPORT_URL: "{{ .Values.autoSupport.url }}"
  TRIDENT_PROTECT_AUTOSUPPORT_PROXY: "{{ .Values.autoSupport.proxy }}"
  TRIDENT_PROTECT_AUTOSUPPORT_INSECURE: "{{ .Values.autoSupport.insecure }}"
  {{- if .Values.autoSupport.image.registry }}
  TRIDENT_PROTECT_AUTOSUPPORT_REGISTRY: "{{ .Values.autoSupport.image.registry }}"
  {{- end }}
  {{- if .Values.autoSupport.image.repository }}
  TRIDENT_PROTECT_AUTOSUPPORT_REPOSITORY: "{{ .Values.autoSupport.image.repository }}"
  {{- end }}
  {{- if .Values.autoSupport.image.tag }}
  TRIDENT_PROTECT_AUTOSUPPORT_TAG: "{{ .Values.autoSupport.image.tag }}"
  {{- end }}
  TRIDENT_PROTECT_NAME_PREFIX: "{{ .Values.namePrefix }}"
  CA_CERT_CONFIGMAP_NAME: "{{ .Values.caCertConfigMap.name }}"
  {{- if .Values.cbs }}
  {{- if .Values.cbs.accountID }}
  TRIDENT_PROTECT_CBS_ACCOUNT_ID: "{{ .Values.cbs.accountID }}"
  {{- end }}
  {{- if .Values.cbs.agentID }}
  TRIDENT_PROTECT_CBS_CONNECTOR_ID: "{{ .Values.cbs.agentID }}"
  {{- end }}
  {{- if .Values.cbs.proxyHostIP }}
  TRIDENT_PROTECT_PROXY_HOST: "{{ .Values.cbs.proxyHostIP }}"
  {{- end }}
  TRIDENT_PROTECT_PROXY_SECRETNAME: "tp-proxy-api-token"
  {{- end }}
  {{- if .Values.vm }}
  TRIDENT_PROTECT_VM_FREEZE: "{{ ne .Values.vm.freeze false }}"
  {{- end }}
  {{- with .Values.customLabels }}
  TRIDENT_PROTECT_LABELS: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.nodeSelector }}
  TRIDENT_PROTECT_NODE_SELECTOR: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.clusterName }}
  TRIDENT_PROTECT_CLUSTER_NAME: "{{ .Values.clusterName }}"
  {{- end }}
  {{- if .Values.restoreSkipNamespaceAnnotations }}
  RESTORE_SKIP_NAMESPACE_ANNOTATIONS: "{{ .Values.restoreSkipNamespaceAnnotations | join "," }}"
  {{- end }}
  {{- if .Values.restoreSkipNamespaceLabels }}
  RESTORE_SKIP_NAMESPACE_LABELS: "{{ .Values.restoreSkipNamespaceLabels | join "," }}"
  {{- end }}
  DEFAULT_JOB_CPU_REQUEST: "{{ .Values.jobResources.defaults.requests.cpu }}"
  DEFAULT_JOB_CPU_LIMIT: "{{ .Values.jobResources.defaults.limits.cpu }}"
  DEFAULT_JOB_MEMORY_REQUEST: "{{ .Values.jobResources.defaults.requests.memory }}"
  DEFAULT_JOB_MEMORY_LIMIT: "{{ .Values.jobResources.defaults.limits.memory }}"
  {{- if .Values.jobResources.defaults.requests.ephemeralStorage }}
  DEFAULT_JOB_EPHEMERAL_STORAGE_REQUEST: "{{ .Values.jobResources.defaults.requests.ephemeralStorage }}"
  {{- end }}
  {{- if .Values.jobResources.defaults.limits.ephemeralStorage }}
  DEFAULT_JOB_EPHEMERAL_STORAGE_LIMIT: "{{ .Values.jobResources.defaults.limits.ephemeralStorage }}"
  {{- end }}

  {{- if .Values.jobResources.resticVolumeBackup.requests.cpu }}
  RESTIC_VOLUME_BACKUP_CPU_REQUEST: "{{ .Values.jobResources.resticVolumeBackup.requests.cpu }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeBackup.requests.memory }}
  RESTIC_VOLUME_BACKUP_MEMORY_REQUEST: "{{ .Values.jobResources.resticVolumeBackup.requests.memory }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeBackup.requests.ephemeralStorage }}
  RESTIC_VOLUME_BACKUP_EPHEMERAL_STORAGE_REQUEST: "{{ .Values.jobResources.resticVolumeBackup.requests.ephemeralStorage }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeBackup.limits.cpu }}
  RESTIC_VOLUME_BACKUP_CPU_LIMIT: "{{ .Values.jobResources.resticVolumeBackup.limits.cpu }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeBackup.limits.memory }}
  RESTIC_VOLUME_BACKUP_MEMORY_LIMIT: "{{ .Values.jobResources.resticVolumeBackup.limits.memory }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeBackup.limits.ephemeralStorage }}
  RESTIC_VOLUME_BACKUP_EPHEMERAL_STORAGE_LIMIT: "{{ .Values.jobResources.resticVolumeBackup.limits.ephemeralStorage }}"
  {{- end }}

  {{- if .Values.jobResources.resticVolumeRestore.requests.cpu }}
  RESTIC_VOLUME_RESTORE_CPU_REQUEST: "{{ .Values.jobResources.resticVolumeRestore.requests.cpu }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeRestore.requests.memory }}
  RESTIC_VOLUME_RESTORE_MEMORY_REQUEST: "{{ .Values.jobResources.resticVolumeRestore.requests.memory }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeRestore.requests.ephemeralStorage }}
  RESTIC_VOLUME_RESTORE_EPHEMERAL_STORAGE_REQUEST: "{{ .Values.jobResources.resticVolumeRestore.requests.ephemeralStorage }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeRestore.limits.cpu }}
  RESTIC_VOLUME_RESTORE_CPU_LIMIT: "{{ .Values.jobResources.resticVolumeRestore.limits.cpu }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeRestore.limits.memory }}
  RESTIC_VOLUME_RESTORE_MEMORY_LIMIT: "{{ .Values.jobResources.resticVolumeRestore.limits.memory }}"
  {{- end }}
  {{- if .Values.jobResources.resticVolumeRestore.limits.ephemeralStorage }}
  RESTIC_VOLUME_RESTORE_EPHEMERAL_STORAGE_LIMIT: "{{ .Values.jobResources.resticVolumeRestore.limits.ephemeralStorage }}"
  {{- end }}

  {{- if .Values.jobResources.kopiaVolumeBackup.requests.cpu }}
  KOPIA_VOLUME_BACKUP_CPU_REQUEST: "{{ .Values.jobResources.kopiaVolumeBackup.requests.cpu }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeBackup.requests.memory }}
  KOPIA_VOLUME_BACKUP_MEMORY_REQUEST: "{{ .Values.jobResources.kopiaVolumeBackup.requests.memory }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeBackup.requests.ephemeralStorage }}
  KOPIA_VOLUME_BACKUP_EPHEMERAL_STORAGE_REQUEST: "{{ .Values.jobResources.kopiaVolumeBackup.requests.ephemeralStorage }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeBackup.limits.cpu }}
  KOPIA_VOLUME_BACKUP_CPU_LIMIT: "{{ .Values.jobResources.kopiaVolumeBackup.limits.cpu }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeBackup.limits.memory }}
  KOPIA_VOLUME_BACKUP_MEMORY_LIMIT: "{{ .Values.jobResources.kopiaVolumeBackup.limits.memory }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeBackup.limits.ephemeralStorage }}
  KOPIA_VOLUME_BACKUP_EPHEMERAL_STORAGE_LIMIT: "{{ .Values.jobResources.kopiaVolumeBackup.limits.ephemeralStorage }}"
  {{- end }}

  {{- if .Values.jobResources.kopiaVolumeRestore.requests.cpu }}
  KOPIA_VOLUME_RESTORE_CPU_REQUEST: "{{ .Values.jobResources.kopiaVolumeRestore.requests.cpu }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeRestore.requests.memory }}
  KOPIA_VOLUME_RESTORE_MEMORY_REQUEST: "{{ .Values.jobResources.kopiaVolumeRestore.requests.memory }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeRestore.requests.ephemeralStorage }}
  KOPIA_VOLUME_RESTORE_EPHEMERAL_STORAGE_REQUEST: "{{ .Values.jobResources.kopiaVolumeRestore.requests.ephemeralStorage }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeRestore.limits.cpu }}
  KOPIA_VOLUME_RESTORE_CPU_LIMIT: "{{ .Values.jobResources.kopiaVolumeRestore.limits.cpu }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeRestore.limits.memory }}
  KOPIA_VOLUME_RESTORE_MEMORY_LIMIT: "{{ .Values.jobResources.kopiaVolumeRestore.limits.memory }}"
  {{- end }}
  {{- if .Values.jobResources.kopiaVolumeRestore.limits.ephemeralStorage }}
  KOPIA_VOLUME_RESTORE_EPHEMERAL_STORAGE_LIMIT: "{{ .Values.jobResources.kopiaVolumeRestore.limits.ephemeralStorage }}"
  {{- end }}
  TRIDENT_PROTECT_CBS_MULTI_BUCKET_SUPPORT_ENABLED: {{ ne (default dict .Values.features).cbsMultiBucketSupport false | quote }}
  TRIDENT_PROTECT_METRICS_SECRETNAME: {{ .Values.webhook.tlsSecretName }}

  {{- if .Values.envVars }}
  {{- range $key, $value := .Values.envVars }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- end }}
