apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "tridentprotect.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- if and .Values.scc.create (.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints") }}
        openshift.io/required-scc: "{{ .Values.scc.name }}"
        {{- end }}
      labels:
        control-plane: controller-manager
        app: controller.protect.trident.netapp.io
        {{- include "tridentprotect.labels" . | nindent 8 }}
    spec:
      {{- $secrets := .Values.controller.imagePullSecrets | default .Values.imagePullSecrets }}
      {{- with $secrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.caCertConfigMap.name }}
        - name: cacert
          configMap:
            name: {{ .Values.caCertConfigMap.name }}
            optional: true
        {{- end }}
        - name: webhook-certs
          secret:
            secretName: {{ .Values.webhook.tlsSecretName }}
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: manager
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8443
          image: {{ include "tridentprotect.fullImage" . }}
          volumeMounts:
            {{- if .Values.caCertConfigMap.name }}
            - name: cacert
              mountPath: /etc/ssl/certs
            {{- end }}
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.namePrefix }}-env-config
          env:
            - name: SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: ENABLE_WEBHOOKS
              value: "true"
            - name: TRIDENT_PROTECT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      serviceAccountName: {{ .Values.namePrefix }}-controller-manager
      terminationGracePeriodSeconds: 10
