apiVersion: v1
kind: Service
metadata:
  labels:
  {{- include "tridentprotect.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.webhook.serviceName }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
      name: https
  selector:
    control-plane: controller-manager
---