{{- if .Values.crCleanup.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.namePrefix }}-cr-cleanup-pre-delete
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tridentprotect.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "5"
spec:
  backoffLimit: 1
  template:
    metadata:
      {{- with .Values.crCleanup.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $global_labels := .Values.customLabels | default dict }}
      {{- $cleanup_labels := .Values.crCleanup.podLabels | default dict }}
      {{- $merged_labels := merge $cleanup_labels $global_labels }}
      labels:
        {{- toYaml $merged_labels | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.namePrefix }}-controller-manager
      {{- with .Values.crCleanup.podSecurityContext }}
      securityContext:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- $secrets := .Values.crCleanup.imagePullSecrets | default .Values.imagePullSecrets }}
      {{- with $secrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: kubectl
          imagePullPolicy: {{ .Values.crCleanup.image.pullPolicy }}
          image: {{ include "tridentprotect.crCleanupImage" . }}
          command:
            - /bin/bash
            - '-c'
            - |-
              PATTERN="protect.trident."
              TIMEOUT={{ .Values.crCleanup.timeout }}
              INTERVAL=10
              START_TIME=$(date +%s)

              kubectl get crd | grep "$PATTERN" | awk '{print $1}' | xargs kubectl delete crd

              echo "Waiting up to $TIMEOUT for Trident-protect CRDs to be deleted..."
              while true; do
                CURRENT_TIME=$(date +%s)
                ELAPSED_TIME=$(( CURRENT_TIME - START_TIME ))
                if [ $ELAPSED_TIME -ge $TIMEOUT ]; then
                  echo "Timeout reached. Trident-protect CRDs matching pattern '$PATTERN' still exist."
                  echo "Still have the following Trident-protect CRDs that exist in the cluster"
                  kubectl get crd -o name | grep "$PATTERN" || true
                  exit 1
                fi

                # Capture the output and exit status of kubectl separately
                CRD_OUTPUT=$(kubectl get crd -o name 2>/dev/null)
                KUBECTL_EXIT_STATUS=$?

                if [ $KUBECTL_EXIT_STATUS -ne 0 ]; then
                  echo "kubectl command failed, will retry..."
                elif echo "$CRD_OUTPUT" | grep -q "$PATTERN"; then
                  echo "Trident-protect CRDs matching pattern '$PATTERN' still exist."
                else
                  echo "No Trident-protect CRDs matching pattern '$PATTERN' found."
                  exit 0
                fi
                sleep $INTERVAL
              done
          {{- with .Values.crCleanup.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.crCleanup.tolerations }}}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- $global := .Values.nodeSelector | default dict }}
      {{- $cleanup := .Values.crCleanup.nodeSelector | default dict }}
      {{- $merged := merge $cleanup $global }}
      nodeSelector:
        {{- toYaml $merged | nindent 8 }}
      {{- if or .Values.crCleanup.podAntiAffinity .Values.crCleanup.podAffinity .Values.crCleanup.nodeAffinity }}
      affinity:
        {{- with .Values.crCleanup.podAntiAffinity }}
        podAntiAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .Values.crCleanup.podAffinity }}
        podAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .Values.crCleanup.nodeAffinity }}
        nodeAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
      {{- end }}
{{- end -}}
