{{- if .Values.webhooksCleanup.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.namePrefix }}-remove-webhook-pre-delete
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tridentprotect.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "100"
spec:
  backoffLimit: 1
  template:
    metadata:
      {{- with .Values.webhooksCleanup.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $global_labels := .Values.customLabels | default dict }}
      {{- $cleanup_labels := .Values.webhooksCleanup.podLabels | default dict }}
      {{- $merged_labels := merge $cleanup_labels $global_labels }}
      labels:
        {{- toYaml $merged_labels | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.namePrefix }}-controller-manager
      {{- with .Values.webhooksCleanup.podSecurityContext }}
      securityContext:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- $secrets := .Values.webhooksCleanup.imagePullSecrets | default .Values.imagePullSecrets }}
      {{- with $secrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: kubectl
          imagePullPolicy: {{ .Values.webhooksCleanup.image.pullPolicy }}
          image: {{ include "tridentprotect.webhooksCleanupImage" . }}
          command:
            - /bin/bash
            - '-c'
            - |-
              set -euo pipefail
              echo "sleeping 3 seconds"
              sleep 3
              kubectl delete validatingwebhookconfiguration -l app.kubernetes.io/name={{ include "tridentprotect.name" . }}
          {{- with .Values.webhooksCleanup.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.webhooksCleanup.tolerations }}}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- $global := .Values.nodeSelector | default dict }}
      {{- $cleanup := .Values.webhooksCleanup.nodeSelector | default dict }}
      {{- $merged := merge $cleanup $global }}
      nodeSelector:
        {{- toYaml $merged | nindent 8 }}
      {{- if or .Values.webhooksCleanup.podAntiAffinity .Values.webhooksCleanup.podAffinity .Values.webhooksCleanup.nodeAffinity }}
      affinity:
        {{- with .Values.webhooksCleanup.podAntiAffinity }}
        podAntiAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .Values.webhooksCleanup.podAffinity }}
        podAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .Values.webhooksCleanup.nodeAffinity }}
        nodeAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
      {{- end }}
{{- end -}}
