{{- if or (not .Values.scc.create) (not (.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints")) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: {{ .Values.namePrefix }}-job-copy
    namespace: {{ .Release.Namespace }}  
rules:
  - apiGroups:
      - ""
    resources:
      - "persistentvolumeclaims"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "delete"
{{- end }}