apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "tridentprotect.labels" . | nindent 4 }}
  name: {{ .Values.namePrefix }}-resourcebackup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namePrefix }}-resourcebackup
subjects:
- kind: ServiceAccount
  name: {{ .Values.namePrefix }}-resourcebackup
  namespace: {{ .Release.Namespace }}
# This is for the ResourceViewerCR; here we can bind our controller-manager ServiceAccount
# to this ClusterRole that already contains all the 
# necessary permissions to do collection.
- kind: ServiceAccount 
  name: {{ .Values.namePrefix }}-controller-manager
  namespace: {{ .Release.Namespace }}
