apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.namePrefix }}-tenant-cluster-role
  labels:
      {{- include "tridentprotect.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - protect.trident.netapp.io
    resources:
    - applications
    - appmirrorrelationships
    - appmirrorupdates
    - appvaulttargets
    - backupinplacerestores
    - backuprestores
    - backups
    - cbsrelationships
    - cbsvolumebackups
    - cbsvolumerestores
    - exechooks
    - exechooksruns
    - kopiavolumebackups
    - kopiavolumerestores
    - pvccopies
    - pvcerases
    - replicatesnapshots
    - replicatesnapshotrestores
    - resourcebackups
    - resourcedeletes
    - resourcerestores
    - resourceviewers
    - resticvolumebackups
    - resticvolumerestores
    - schedules
    - shutdownsnapshots
    - snapshotinplacerestores
    - snapshotrestores
    - snapshots
    verbs:
    - '*'
