apiVersion: v2
appVersion: 25.10.0
description: NetApp's Trident protect helm chart for Kubernetes Data Management.
kubeVersion: '>= 1.24.0-0'
name: trident-protect
type: application
version: 100.2510.0
