autoSupport:
  enabled: true
  insecure: false
  proxy: ""
  url: "https://support.netapp.com/put/AsupPut"
  image:
    registry: ""
    repository: ""
    tag: ""

clusterName: ""

logLevel: ""

controller:
  image:
    # -- Image registry, defaults to global imageRegistry if omitted
    registry: ~
    repository: "controller"
    pullPolicy: IfNotPresent
    tag: ""
    # -- Image pull secrets, defaults to global imagePullSecrets if omitted
    imagePullSecrets: []
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: ".5"
      memory: 2Gi
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault

nodeSelector:
  kubernetes.io/os: linux

customLabels: {}

jobResources:
  defaults:
    limits:
      cpu: "8000m"
      memory: "10000Mi"
      ephemeralStorage: ""
    requests:
      cpu: "100m"
      memory: "100Mi"
      ephemeralStorage: ""

  # -- Adding placeholder for the jobs that would likely be overwritten by the user.
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""

imagePullSecrets: []
imageRegistry: "netapp"

nameOverride: "trident-protect"

caCertConfigMap:
  name: ""

scc:
  create: true
  name: trident-protect-job
  priority: 1

webhook:
  serviceName: tp-webhook-service
  tlsSecretName: tp-webhook-tls

# https://github.com/helm/helm/issues/12360
webhooksCleanup:
  # -- Create a helm pre-delete hook to cleanup webhooks.
  enabled: true

  image:
    # -- Image registry, defaults to imageRegistry if omitted
    registry: ~
    # -- Image repository
    repository: trident-protect-utils
    # -- Image tag
    tag: 'v1.0.0'
    # -- Image pull policy
    pullPolicy: ~

  # -- Image pull secrets, defaults to global imagePullSecrets if omitted
  imagePullSecrets: []

  # -- Security context for the pod
  podSecurityContext: {}

  # -- Node labels for pod assignment
  nodeSelector: {}

  # -- List of node taints to tolerate
  tolerations: []

  # -- Pod anti affinity constraints.
  podAntiAffinity: {}

  # -- Pod affinity constraints.
  podAffinity: {}

  # -- Pod labels.
  podLabels: {}

  # -- Pod annotations.
  podAnnotations: {}

  # -- Node affinity constraints.
  nodeAffinity: {}

  # -- Security context for the hook containers
  securityContext:
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    allowPrivilegeEscalation: false
  # Note: Potential values for securityContext:
  #    runAsUser: 65534
  #    runAsGroup: 65534
  #    runAsNonRoot: true
  #    privileged: false
  #    readOnlyRootFilesystem: true


crCleanup:
  # -- Create a helm pre-delete hook to wait for CRDs to be removed.
  enabled: true

  # -- Timeout in seconds to wait for CRDs to be removed.
  timeout: 600

  image:
    # -- Image registry, defaults to global imageRegistry if omitted
    registry: ~
    # -- Image repository
    repository: trident-protect-utils
    # -- Image tag
    tag: 'v1.0.0'
    # -- Image pull policy
    pullPolicy: ~

  # -- Image pull secrets, defaults to global imagePullSecrets if omitted
  imagePullSecrets: []

  # -- Security context for the pod
  podSecurityContext: {}

  # -- Node labels for pod assignment
  nodeSelector: {}

  # -- List of node taints to tolerate
  tolerations: []

  # -- Pod anti affinity constraints.
  podAntiAffinity: {}

  # -- Pod affinity constraints.
  podAffinity: {}

  # -- Pod labels.
  podLabels: {}

  # -- Pod annotations.
  podAnnotations: {}

  # -- Node affinity constraints.
  nodeAffinity: {}

  # -- Security context for the hook containers
  securityContext:
    capabilities:
      drop:
      - ALL
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    allowPrivilegeEscalation: false
  # Note: Potential values for securityContext:
  #    runAsUser: 65534
  #    runAsGroup: 65534
  #    runAsNonRoot: true
  #    privileged: false
  #    readOnlyRootFilesystem: true

namePrefix: "trident-protect"

# Comma-separated list of namespace annotations to skip during restore
restoreSkipNamespaceAnnotations: []

# Comma-separated list of namespace labels to skip during restore
restoreSkipNamespaceLabels: []

# VM freeze configuration
vm:
  freeze: true
